//! Security, Sandbox, and Governance Test Suite

#[path = "../adversarial_blueprint_challenge.rs"]
pub mod adversarial_blueprint_challenge;
#[path = "../adversarial_challenger_e2e_tests.rs"]
pub mod adversarial_challenger_e2e_tests;
#[path = "../adversarial_debt_challenge_tests.rs"]
pub mod adversarial_debt_challenge_tests;
#[path = "../artifact_trust.rs"]
pub mod artifact_trust;
#[path = "../cognitive_adversarial_challenge.rs"]
pub mod cognitive_adversarial_challenge;
#[path = "../cognitive_adversarial_tests.rs"]
pub mod cognitive_adversarial_tests;
#[path = "../cognitive_runtime_tests.rs"]
pub mod cognitive_runtime_tests;
#[path = "../command_authorization.rs"]
pub mod command_authorization;
#[path = "../cua_ipc_integration.rs"]
pub mod cua_ipc_integration;
#[path = "../cua_m4_thread_leak_challenge.rs"]
pub mod cua_m4_thread_leak_challenge;
#[path = "../integration_tests.rs"]
pub mod integration_tests;
#[path = "../liva_eval_tests.rs"]
pub mod liva_eval_tests;
#[path = "../m2_redaction_adversarial_challenge.rs"]
pub mod m2_redaction_adversarial_challenge;
#[path = "../m3_ipc_sync_adversarial_challenge.rs"]
pub mod m3_ipc_sync_adversarial_challenge;
#[path = "../m4_cua_ipc_adversarial_challenge.rs"]
pub mod m4_cua_ipc_adversarial_challenge;
#[path = "../mcp_client_e2e.rs"]
pub mod mcp_client_e2e;
#[path = "../mcp_vault_sandbox_escape.rs"]
pub mod mcp_vault_sandbox_escape;
#[path = "../normalizer_adversarial_stress.rs"]
pub mod normalizer_adversarial_stress;
#[path = "../panic_cleanup.rs"]
pub mod panic_cleanup;
#[path = "../runtime_stability_tests.rs"]
pub mod runtime_stability_tests;
#[cfg(feature = "experimental")]
#[path = "../sandbox_stress.rs"]
pub mod sandbox_stress;
#[path = "../verify_commands.rs"]
pub mod verify_commands;
#[path = "../websocket_transport.rs"]
pub mod websocket_transport;
