//! Voice, Audio, and Wake Word Test Suite

#[path = "../audio_buffer_vad_adversarial_stress.rs"]
pub mod audio_buffer_vad_adversarial_stress;
#[path = "../debounce_residue_adversarial_stress.rs"]
pub mod debounce_residue_adversarial_stress;
#[path = "../duplex_bargein_stress.rs"]
pub mod duplex_bargein_stress;
#[path = "../fast_voice_sla_tests.rs"]
pub mod fast_voice_sla_tests;
#[path = "../m1_audio_panic_adversarial_challenge.rs"]
pub mod m1_audio_panic_adversarial_challenge;
#[path = "../m1_voice_pipeline_empirical_challenge.rs"]
pub mod m1_voice_pipeline_empirical_challenge;
#[path = "../m2_voice_duplex_adversarial_challenge.rs"]
pub mod m2_voice_duplex_adversarial_challenge;
#[path = "../parakeet_streaming_challenge.rs"]
pub mod parakeet_streaming_challenge;
#[path = "../sla_voice_avatar_benchmark.rs"]
pub mod sla_voice_avatar_benchmark;
#[path = "../stt_adversarial_stress.rs"]
pub mod stt_adversarial_stress;
#[path = "../stt_latency_bench.rs"]
pub mod stt_latency_bench;
#[path = "../task_cancellation_aec_adversarial_stress.rs"]
pub mod task_cancellation_aec_adversarial_stress;
#[path = "../turn_telemetry_tests.rs"]
pub mod turn_telemetry_tests;
#[path = "../vad_adversarial_stress.rs"]
pub mod vad_adversarial_stress;
#[path = "../voice_coordinator_adversarial_stress.rs"]
pub mod voice_coordinator_adversarial_stress;
#[path = "../voice_messaging_dialogue.rs"]
pub mod voice_messaging_dialogue;
#[path = "../voice_runtime_components.rs"]
pub mod voice_runtime_components;
#[path = "../wake_empirical_benchmark.rs"]
pub mod wake_empirical_benchmark;
#[path = "../wake_empirical_edge_cases.rs"]
pub mod wake_empirical_edge_cases;
#[path = "../wake_stress_boundary.rs"]
pub mod wake_stress_boundary;
