//! Core Type Definitions & Protocol Specification for Multi-Agent Swarm
//!
//! Defines specialized agent roles, priority messages, payload taxonomy,
//! granular diff hunks, actor lifecycle states, and errors.

use super::consensus::{ConsensusOutcome, ConsensusRule, VoteDecision};
use super::delegation::DelegationToken;
use super::vector_clock::VectorClock;
use crate::agent::graph::checkpoint::JsonPatchOp;
use crate::sandbox::policy::CapabilityToken;
use serde::{Deserialize, Serialize};
use serde_json::Value;
use std::fmt;

/// The 5 specialized roles forming the multi-agent swarm division of labor.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord, Serialize, Deserialize)]
pub enum SwarmRole {
    /// High-level goal decomposition, sub-task planning, capability assignment, token budgets.
    Planner,
    /// Code generation, tool execution, hunk diff generation, active execution.
    Coder,
    /// Static code review, logic correctness verification, hunk approval/rejection.
    Reviewer,
    /// Security audit, capability compliance, taint tracking, invariant verification.
    Auditor,
    /// System safety guardian, resource limit enforcer, holds UNCONDITIONAL VETO authority.
    Sentinel,
}

impl SwarmRole {
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::Planner => "planner",
            Self::Coder => "coder",
            Self::Reviewer => "reviewer",
            Self::Auditor => "auditor",
            Self::Sentinel => "sentinel",
        }
    }
}

impl fmt::Display for SwarmRole {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.as_str())
    }
}

/// Message priority tiers for lock-free multi-channel mailboxes.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub enum MessagePriority {
    /// Background telemetry, heartbeats, non-blocking metrics.
    Low = 0,
    /// Standard task execution, review feedback, audit reports.
    Normal = 1,
    /// Critical signals, Sentinel vetoes, urgent consensus votes.
    High = 2,
}

/// Status of an individual code change diff hunk.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub enum HunkStatus {
    Pending,
    Approved,
    Rejected { reason: String },
    Modified { user_override: String },
}

/// Granular line-by-line diff hunk structure supporting Living Canvas interactive approval.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct DiffHunk {
    pub hunk_id: String,
    pub file_path: String,
    pub old_start: usize,
    pub old_lines: usize,
    pub new_start: usize,
    pub new_lines: usize,
    pub header: String,
    pub diff_content: String,
    pub status: HunkStatus,
}

impl DiffHunk {
    pub fn new(
        hunk_id: impl Into<String>,
        file_path: impl Into<String>,
        old_start: usize,
        old_lines: usize,
        new_start: usize,
        new_lines: usize,
        header: impl Into<String>,
        diff_content: impl Into<String>,
    ) -> Self {
        Self {
            hunk_id: hunk_id.into(),
            file_path: file_path.into(),
            old_start,
            old_lines,
            new_start,
            new_lines,
            header: header.into(),
            diff_content: diff_content.into(),
            status: HunkStatus::Pending,
        }
    }
}

/// Exhaustive payload taxonomy for all inter-agent operations.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum SwarmPayload {
    /// Task proposal dispatched by Planner or peer delegator.
    TaskProposal {
        task_id: String,
        goal: String,
        description: String,
        required_capabilities: Vec<CapabilityToken>,
        assigned_to: Option<SwarmRole>,
        budget_tokens: u64,
    },
    /// Intermediate or final execution progress of an assigned task.
    TaskProgress {
        task_id: String,
        step_index: usize,
        status: String,
        output: Option<Value>,
    },
    /// Concrete source code changes generated by Coder as a set of diff hunks.
    CodeHunkPatch {
        patch_id: String,
        task_id: String,
        file_path: String,
        hunks: Vec<DiffHunk>,
        summary: String,
    },
    /// Reviewer feedback and verdict on a proposed code hunk patch.
    ReviewVerdict {
        patch_id: String,
        approved: bool,
        feedback: String,
        required_changes: Vec<String>,
    },
    /// Auditor security analysis and capability compliance report.
    AuditReport {
        patch_id: String,
        clean: bool,
        integrity_violations: Vec<String>,
        risk_score: f32,
    },
    /// Sentinel unconditional veto signal halting execution and triggering state rollback.
    SentinelVeto {
        veto_id: String,
        target_id: String,
        reason: String,
        violated_invariant: String,
    },
    /// Proposal for multi-agent quorum vote.
    ConsensusProposal {
        vote_id: String,
        rule: ConsensusRule,
        subject: String,
        payload_digest: String,
        deadline_ms: u64,
    },
    /// Individual vote cast by a swarm actor.
    ConsensusVote {
        vote_id: String,
        voter: SwarmRole,
        decision: VoteDecision,
        reason: Option<String>,
    },
    /// Final consensus decision reached by quorum engine.
    ConsensusResult {
        vote_id: String,
        outcome: ConsensusOutcome,
        summary: String,
    },
    /// State synchronization payload with RFC 6902 patch and causal author.
    StateSync {
        base_version: u64,
        patch: Vec<JsonPatchOp>,
        author: SwarmRole,
    },
    /// Actor health and status heartbeat.
    Heartbeat {
        role: SwarmRole,
        status: ActorStatus,
        active_task: Option<String>,
        ram_usage_bytes: u64,
    },
    /// General extensible payload for custom coordination signals.
    General {
        action: String,
        data: Value,
    },
}

/// Structured message transmitted between swarm actors.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct SwarmMessage {
    pub message_id: String,
    pub trace_id: String,
    pub sender_role: SwarmRole,
    /// Destination role (None indicates a broadcast to all registered swarm actors).
    pub target_role: Option<SwarmRole>,
    pub priority: MessagePriority,
    pub payload: SwarmPayload,
    pub vector_clock: VectorClock,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub delegation_token: Option<DelegationToken>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub correlation_id: Option<String>,
    pub timestamp_ms: u64,
}

impl SwarmMessage {
    pub fn new(
        sender_role: SwarmRole,
        target_role: Option<SwarmRole>,
        priority: MessagePriority,
        payload: SwarmPayload,
        vector_clock: VectorClock,
    ) -> Self {
        let now = chrono::Utc::now().timestamp_millis() as u64;
        let id = format!("msg-{}", uuid::Uuid::new_v4());
        Self {
            message_id: id.clone(),
            trace_id: format!("trc-{}", uuid::Uuid::new_v4()),
            sender_role,
            target_role,
            priority,
            payload,
            vector_clock,
            delegation_token: None,
            correlation_id: None,
            timestamp_ms: now,
        }
    }

    pub fn with_delegation(mut self, token: DelegationToken) -> Self {
        self.delegation_token = Some(token);
        self
    }

    pub fn with_correlation(mut self, correlation_id: impl Into<String>) -> Self {
        self.correlation_id = Some(correlation_id.into());
        self
    }

    pub fn with_trace(mut self, trace_id: impl Into<String>) -> Self {
        self.trace_id = trace_id.into();
        self
    }
}

/// Lifecycle execution state of an individual SwarmActor.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum ActorStatus {
    Idle,
    Busy,
    Suspended,
    Terminated,
    Error(String),
}

/// Swarm actor subsystem errors.
#[derive(Debug, thiserror::Error, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum ActorError {
    #[error("Mailbox send error: {0}")]
    MailboxSendError(String),

    #[error("Mailbox closed")]
    MailboxClosed,

    #[error("Unauthorized capability: {0}")]
    UnauthorizedCapability(String),

    #[error("Delegation token expired or invalid")]
    DelegationExpired,

    #[error("Execution vetoed by Sentinel: {0}")]
    VetoReceived(String),

    #[error("Execution failure: {0}")]
    ExecutionFailure(String),

    #[error("Operation timed out: {0}")]
    Timeout(String),

    #[error("Actor error: {0}")]
    Other(String),
}
