sonar.projectKey=Liva
sonar.host.url=http://localhost:9000
# Anh nhớ giữ nguyên token cũ của Anh ở dòng này nhé
sonar.token=sqp_ad847f6a02c775442f61d056b07b91e9f6d9a998

# Vẫn quét thư mục hiện tại nhưng...
sonar.sources=.

# ...Áp dụng tấm khiên loại trừ cực mạnh (Strict Exclusions)
# Lệnh này sẽ chặn Sonar rớ tới các thư mục data, logs, môi trường ảo và thư viện
sonar.exclusions=**/node_modules/**,**/dist/**,**/logs/**,**/liva-dataset/**,**/data/**,**/scratch_workspace/**,**/shadow_workspace/**,**/mempalace/**,**/*.json,**/*.md,**/*.csv,**/*.pyc,**/src_backup/**,**/tests/_legacy/**,**/scripts/**,**/liva-ai-engine/venv/**,**/liva-ai-engine/native_lib/**,**/*.log,**/*.proto

# Ép Node.js được phép dùng tới 6GB RAM (6144 MB) thay vì mức mặc định
sonar.javascript.node.maxspace=6144