import { z } from "zod";

export const SingularityHypothesisSchema = z.object({
    targetFilePath: z.string(),
    idea: z.string(),
    shell_commands: z.array(z.string()),
    pros: z.string(),
    cons: z.string(),
    testingStrategy: z.string(),
    rollbackPlan: z.string(),
    feasibilityScore: z.union([z.string(), z.number()]).transform(v => String(v)),
    testCommand: z.string()
});

export type SingularityHypothesis = z.infer<typeof SingularityHypothesisSchema>;

export interface EvolutionContext {
    iteration: number;
    hasBugs: boolean;
    
    // Data gathered from scanning
    projectSurfaceInfo: string;
    bottlenecks: string;
    pastExperiences: string;
    axioms: string;
    blacklistFiles: string[];

    // Idea generated by Planner
    hypothesis?: SingularityHypothesis;

    // Execution state
    compilationPassed: boolean;
    errorMsg?: string;
    
    // Checkpoint info
    workspaceDir: string;
}
