export default {
  preset: 'ts-jest',
  testEnvironment: 'node',
  resolver: '<rootDir>/tests/resolver.cjs',
  moduleNameMapper: {
    '^node:(.*)$': '$1',
    '^(\\.\\.?\\/.*)\\.js$': '$1',
    '^@skills/(.*)\\.js$': '<rootDir>/src/skills/$1',
    '^@skills/(.*)$': '<rootDir>/src/skills/$1',
    '^@utils/(.*)\\.js$': '<rootDir>/src/utils/$1',
    '^@utils/(.*)$': '<rootDir>/src/utils/$1',
    '^@core/(.*)\\.js$': '<rootDir>/src/core/$1',
    '^@core/(.*)$': '<rootDir>/src/core/$1',
    '^@memory/(.*)\\.js$': '<rootDir>/src/memory/$1',
    '^@memory/(.*)$': '<rootDir>/src/memory/$1',
    '^@security/(.*)\\.js$': '<rootDir>/src/security/$1',
    '^@security/(.*)$': '<rootDir>/src/security/$1',
    '^@mcp/(.*)\\.js$': '<rootDir>/src/mcp/$1',
    '^@mcp/(.*)$': '<rootDir>/src/mcp/$1',
    '^@services/(.*)\\.js$': '<rootDir>/src/services/$1',
    '^@services/(.*)$': '<rootDir>/src/services/$1',
    '^@evolution/(.*)\\.js$': '<rootDir>/src/evolution/$1',
    '^@evolution/(.*)$': '<rootDir>/src/evolution/$1',
    '^@sandbox/(.*)\\.js$': '<rootDir>/src/sandbox/$1',
    '^@sandbox/(.*)$': '<rootDir>/src/sandbox/$1',
    '^@deployment/(.*)\\.js$': '<rootDir>/src/deployment/$1',
    '^@deployment/(.*)$': '<rootDir>/src/deployment/$1',
    '^vitest$': '<rootDir>/tests/vitest-compat-bridge.ts',
    '^sqlite-vec$': '<rootDir>/tests/sqlite-vec-compat.ts',
  },
  transform: {
    '^.+\\.tsx?$': '<rootDir>/tests/jest-transformer.js',
  },
  globalTeardown: '<rootDir>/tests/globalTeardown.ts',
  setupFilesAfterEnv: ['<rootDir>/tests/setup.ts'],
  testMatch: ['<rootDir>/tests/**/*.test.ts'],
};
