import { DatabaseSync } from 'node:sqlite';
import * as path from 'path';
import * as fs from 'fs';

console.log('=== Cleaning LIVA Structured Memory Database (Global) ===');
const pathsToTry = [
    path.join('data', 'global', 'structured_memory.sqlite'),
    path.join('..', 'data', 'global', 'structured_memory.sqlite'),
    path.join('e:', 'Project', 'LIVA', 'liva-gateway', 'data', 'global', 'structured_memory.sqlite'),
    path.join('e:', 'Project', 'LIVA', 'data', 'global', 'structured_memory.sqlite')
];

let dbPath = '';
for (const p of pathsToTry) {
    if (fs.existsSync(p)) {
        dbPath = p;
        break;
    }
}

if (!dbPath) {
    console.error('❌ Database file not found at any tried path.');
    process.exit(1);
}

console.log(`Using database at: ${dbPath}`);

try {
    const db = new DatabaseSync(dbPath);
    
    // Get all facts
    const facts = db.prepare("SELECT key, value, category, importance FROM facts").all();
    console.log(`\nFound ${facts.length} facts:`);
    for (const fact of facts) {
        console.log(`- [${fact.category}] ${fact.key}: ${fact.value} (importance: ${fact.importance})`);
    }
    
    // We want to delete any weather or irrelevant facts that were generated by testing
    console.log('\nScanning for facts to clean...');
    let deletedCount = 0;
    for (const fact of facts) {
        const keyLower = fact.key.toLowerCase();
        const valLower = fact.value.toLowerCase();
        
        // Match key or value containing weather/hanoi/temp/32.2/beer
        if (keyLower.includes('weather') || keyLower.includes('hanoi') || keyLower.includes('temp') ||
            valLower.includes('weather') || valLower.includes('hà nội') || valLower.includes('32.2°c') ||
            valLower.includes('mây rải rác') || valLower.includes('bia hơi') || valLower.includes('nắng nóng')
        ) {
            console.log(`❌ Deleting fact: ${fact.key} (Value: ${fact.value})`);
            db.prepare("DELETE FROM facts WHERE key = ?").run(fact.key);
            deletedCount++;
        }
    }
    
    console.log(`\nCleaned ${deletedCount} incorrect/test facts.`);
    
} catch (err) {
    console.error('❌ Error:', err.message);
}
