import { logger } from "../utils/logger";

/**
 * [LIVA V2 Singularity] SSGM - Stability and Safety Governed Memory
 * Write Validation Gate / Truth Maintenance System (TMS)
 * Ensures that any proposed memory updates (ΔM) do not logically contradict the Core Facts (M_core).
 */
export class WriteValidationGate {
    private static instance: WriteValidationGate;

    private constructor() {}

    public static getInstance(): WriteValidationGate {
        if (!WriteValidationGate.instance) {
            WriteValidationGate.instance = new WriteValidationGate();
        }
        return WriteValidationGate.instance;
    }

    /**
     * Validates a proposed memory update against core facts using Natural Language Inference (NLI) simulation.
     * @param proposedFact The new fact or memory delta (ΔM) generated by an Agent
     * @param coreFacts Array of immutable core facts (M_core) from the episodic log
     * @returns boolean true if safe to consolidate, false if semantic drift/contradiction is detected
     */
    public async validateUpdate(proposedFact: string, coreFacts: string[]): Promise<boolean> {
        if (!proposedFact || coreFacts.length === 0) {
            return true; // Nothing to contradict
        }

        logger.info(`[SSGM] 🛡️ Validating proposed memory update: "${proposedFact.substring(0, 50)}..."`);

        try {
            // TODO: Integrate actual NLI model evaluation here (e.g., using LIVA's Expert Model)
            // For Phase 1, we use a heuristic / placeholder for contradiction detection.
            
            // Simulated validation delay
            await new Promise(resolve => setTimeout(resolve, 50));
            
            // Example basic heuristic: If proposed fact directly negates a core fact
            for (const core of coreFacts) {
                if (this.detectContradiction(proposedFact, core)) {
                    logger.warn(`[SSGM] 🛑 Memory Poisoning Blocked! Proposed fact contradicts core fact: "${core}"`);
                    return false;
                }
            }

            logger.info(`[SSGM] ✅ Validation passed. Memory update is safe for consolidation.`);
            return true;
        } catch (error: unknown) {
            const errMsg = error instanceof Error ? error.message : String(error);
            logger.error(`[SSGM] ❌ Validation Gate failed to process: ${errMsg}`);
            return false; // Fail secure
        }
    }

    private detectContradiction(proposed: string, core: string): boolean {
        const pNorm = proposed.toLowerCase().trim();
        const cNorm = core.toLowerCase().trim();
        
        // Simple direct negation heuristic in English and Vietnamese
        const negations = [
            /\bkhông phải\b/i, /\bkhông\b/i, /\bchưa\b/i, /\bnot\b/i, /\bnever\b/i, 
            /\bisnot\b/i, /\bdoes not\b/i, /\bdoesn't\b/i,
            /\bdon't\b/i, /\bdo not\b/i, /\bwon't\b/i, /\bwill not\b/i
        ];
        
        const hasPNeg = negations.some(regex => regex.test(pNorm));
        const hasCNeg = negations.some(regex => regex.test(cNorm));
        
        // If one is negated and the other is not, check word overlap
        if (hasPNeg !== hasCNeg) {
            const stripNegations = (text: string) => {
                let cleaned = text;
                negations.forEach(regex => {
                    cleaned = cleaned.replace(new RegExp(regex.source, "gi"), "");
                });
                return cleaned.replace(/\s+/g, " ").trim();
            };
            
            const getWords = (text: string) => {
                const clean = stripNegations(text);
                return clean.split(/\s+/)
                    .map(w => w.replace(/[^a-z0-9àáạảãâầấậẩẫăằắặẳẵèéẹẻẽêềếệểễìíịỉĩòóọỏõôồốộổỗơờớợởỡùúụủũưừứựửữỳýỵỷỹđ]/g, "")) // keep alphanumeric including Vietnamese characters
                    .filter(w => w.length > 2 && !["does", "hãy", "cho", "là", "bản", "the", "and"].includes(w));
            };
            
            const wordsP = getWords(pNorm);
            const wordsC = getWords(cNorm);
            
            if (wordsP.length > 0 && wordsC.length > 0) {
                const shorter = wordsP.length < wordsC.length ? wordsP : wordsC;
                const longer = wordsP.length < wordsC.length ? wordsC : wordsP;
                
                const wordsMatch = (w1: string, w2: string) => {
                    if (w1 === w2) return true;
                    const stem = (w: string) => {
                        let s = w;
                        if (s.endsWith("ing")) {
                            s = s.slice(0, -3);
                        } else if (s.endsWith("ed")) {
                            s = s.slice(0, -2);
                        } else if (s.endsWith("ies")) {
                            s = s.slice(0, -3) + "y";
                        } else if (s.endsWith("s") && !s.endsWith("ss") && !s.endsWith("us") && !s.endsWith("as")) {
                            s = s.slice(0, -1);
                        }
                        return s;
                    };
                    return stem(w1) === stem(w2);
                };
                
                const matches = shorter.filter(w1 => longer.some(w2 => wordsMatch(w1, w2)));
                const overlapRatio = matches.length / shorter.length;
                if (overlapRatio >= 0.75) {
                    return true;
                }
            }
        }
        
        return false;
    }
}
