# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import liva_engine_pb2 as liva__engine__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in liva_engine_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LivaInferenceServiceStub(object):
    """=============================================================
    LIVA Inference Engine — gRPC Protocol Definition
    Replaces TCP/JSONL with binary Protobuf over HTTP/2
    =============================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamChat = channel.unary_stream(
                '/liva.LivaInferenceService/StreamChat',
                request_serializer=liva__engine__pb2.ChatCompletionRequest.SerializeToString,
                response_deserializer=liva__engine__pb2.ChatCompletionChunk.FromString,
                _registered_method=True)
        self.Chat = channel.unary_unary(
                '/liva.LivaInferenceService/Chat',
                request_serializer=liva__engine__pb2.ChatCompletionRequest.SerializeToString,
                response_deserializer=liva__engine__pb2.ChatCompletionResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/liva.LivaInferenceService/HealthCheck',
                request_serializer=liva__engine__pb2.HealthRequest.SerializeToString,
                response_deserializer=liva__engine__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.Embed = channel.unary_unary(
                '/liva.LivaInferenceService/Embed',
                request_serializer=liva__engine__pb2.EmbeddingRequest.SerializeToString,
                response_deserializer=liva__engine__pb2.EmbeddingResponse.FromString,
                _registered_method=True)
        self.SwapModel = channel.unary_unary(
                '/liva.LivaInferenceService/SwapModel',
                request_serializer=liva__engine__pb2.SwapModelRequest.SerializeToString,
                response_deserializer=liva__engine__pb2.SwapModelResponse.FromString,
                _registered_method=True)


class LivaInferenceServiceServicer(object):
    """=============================================================
    LIVA Inference Engine — gRPC Protocol Definition
    Replaces TCP/JSONL with binary Protobuf over HTTP/2
    =============================================================

    """

    def StreamChat(self, request, context):
        """Server-Streaming RPC: Gateway sends one request, Engine streams tokens back
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Chat(self, request, context):
        """Unary RPC: Non-streaming completion (for short prompts)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Embed(self, request, context):
        """Embedding RPC: Generate L2-normalized embeddings via shared GPU context
        Supports batch input (repeated string) for ConsolidationCron throughput
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SwapModel(self, request, context):
        """[v29] Hot-Swap RPC: Unload current model, load new model (sequential single-model on VRAM)
        Used by ModelOrchestrator to swap Router↔Expert without restarting the engine process
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LivaInferenceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamChat': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamChat,
                    request_deserializer=liva__engine__pb2.ChatCompletionRequest.FromString,
                    response_serializer=liva__engine__pb2.ChatCompletionChunk.SerializeToString,
            ),
            'Chat': grpc.unary_unary_rpc_method_handler(
                    servicer.Chat,
                    request_deserializer=liva__engine__pb2.ChatCompletionRequest.FromString,
                    response_serializer=liva__engine__pb2.ChatCompletionResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=liva__engine__pb2.HealthRequest.FromString,
                    response_serializer=liva__engine__pb2.HealthResponse.SerializeToString,
            ),
            'Embed': grpc.unary_unary_rpc_method_handler(
                    servicer.Embed,
                    request_deserializer=liva__engine__pb2.EmbeddingRequest.FromString,
                    response_serializer=liva__engine__pb2.EmbeddingResponse.SerializeToString,
            ),
            'SwapModel': grpc.unary_unary_rpc_method_handler(
                    servicer.SwapModel,
                    request_deserializer=liva__engine__pb2.SwapModelRequest.FromString,
                    response_serializer=liva__engine__pb2.SwapModelResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'liva.LivaInferenceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('liva.LivaInferenceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LivaInferenceService(object):
    """=============================================================
    LIVA Inference Engine — gRPC Protocol Definition
    Replaces TCP/JSONL with binary Protobuf over HTTP/2
    =============================================================

    """

    @staticmethod
    def StreamChat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/liva.LivaInferenceService/StreamChat',
            liva__engine__pb2.ChatCompletionRequest.SerializeToString,
            liva__engine__pb2.ChatCompletionChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Chat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/liva.LivaInferenceService/Chat',
            liva__engine__pb2.ChatCompletionRequest.SerializeToString,
            liva__engine__pb2.ChatCompletionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/liva.LivaInferenceService/HealthCheck',
            liva__engine__pb2.HealthRequest.SerializeToString,
            liva__engine__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Embed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/liva.LivaInferenceService/Embed',
            liva__engine__pb2.EmbeddingRequest.SerializeToString,
            liva__engine__pb2.EmbeddingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SwapModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/liva.LivaInferenceService/SwapModel',
            liva__engine__pb2.SwapModelRequest.SerializeToString,
            liva__engine__pb2.SwapModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
